apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
configMapGenerator:
- literals:
  - NEXT_PUBLIC_NETWORK_ID=testnet
  - NEXT_PUBLIC_HOSTNAME=https://cali-bos.euw3.dev.gcp.calimero.network
  name: cali-bos
resources:
- ../../../base-0.0.0
- host.yaml
- mapping.yaml
images:
- name: cali-bos
  newName: europe-west3-docker.pkg.dev/calimero-ops/calimero/cali-bos
  newTag: 5c44446
