apiVersion: apps/v1
kind: Deployment
metadata:
  name: bos-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bos-gateway
          image: bos-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          # TODO: implement liveness and readiness probes
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 3000
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /health
          #     port: 3000
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: bos-gateway
            - secretRef:
                name: bos-gateway
