# - op: replace
#   path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
#   value: bos-gateway-portal
- op: replace
  path: /spec/template/spec/containers/0/image
  value: bos-gateway-mainnet:latest
