apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cali-public-portal-calimero
commonLabels:
  app.kubernetes.io/name: bos-gateway
  app.kubernetes.io/component: bos
  app.kubernetes.io/instance: public
resources:
  - ../../../../base-0.0.0
  - certificate.yaml
  - frontend-config.yaml
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
